kindling:
  telemetry:
    logging:
      level: CRITICAL

datapipes:
  bronze.ingest_telemetry:
    tags:
      placement.source: app
    output_type: delta
  silver.build_telemetry:
    tags:
      placement.source: app
    output_type: delta
  silver.derive_events:
    tags:
      placement.source: app
    output_type: delta
  silver.derive_episodes:
    tags:
      placement.source: app
    output_type: delta
