name: Feature Request / Enhancement
description: Suggest a new feature or improvement to existing functionality
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Use this for new features OR enhancements to existing functionality.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this target?
      options:
        - All Platforms
        - Fabric
        - Synapse
        - Databricks
        - Not Platform-Specific
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What pain point does this address?
      placeholder: |
        Example: "Currently, deploying jobs requires manual configuration of..."
        Or: "I need to track work for..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution or enhancement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Have you considered any other solutions or workarounds?
      placeholder: Describe alternative approaches you've considered
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know when this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests passing
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, examples, or references
    validations:
      required: false
