kindling:
  storage:
    table_naming: leaf
    table_schema: cwmdp
  telemetry:
    logging:
      level: ERROR

dataentities:
  "bronze.**":
    tags:
      provider.table_catalog: dev_bronze
      placement.source: environment
  "silver.**":
    tags:
      provider.table_catalog: dev_silver
      placement.source: environment
  "gold.**":
    tags:
      provider.table_catalog: dev_gold
      placement.source: environment
  "reference.**":
    tags:
      provider.table_catalog: dev_reference
      placement.source: environment
