"""Generic Lakeflow pipeline source generated by kindling bundle build.

The pipeline configuration selects the Kindling data app and carries its
effective settings; this file only hands control to the selector.
"""

from kindling_ext_databricks.lakeflow_app_selector import declare_from_pipeline_config

declare_from_pipeline_config()
